default:
  interval: 4
  dev: TRUE
  informed: FALSE
  n_iter: 1000
  mcmc_config: "mostlyDefault"
  data_repo: "C:/Users/John.Foster/OneDrive - USDA/Desktop/fosteR/pigs-statistical/data"
  file_mis: "insitu/MIS.Effort.Take.All.Methods.Daily.Events.2021-03-25.csv"
  file_land: 'covariates/FINAL.Process.Model.Observation.Covariates.12Jan2018.csv'
  file_post: "C:/Users/John.Foster/Downloads/22_properties_combined/posteriorSamples.rds"

hpc_dev:
  data_repo: "/lustrefs/ceah/feral-swine/data"
  file_post: "/lustrefs/ceah/feral-swine/property-fits/dev/64properties_uninformedPriors_combined/posteriorSamples.rds"
  n_iter: 50000
