default:
  interval: 4
  dev: TRUE
  np: 300
  n_iter: 1000
  data_repo: "C:/Users/John.Foster/OneDrive - USDA/Desktop/fosteR/pigs-statistical/data"
  file_mis: "insitu/MIS.Effort.Take.All.Methods.Daily.Events.2021-03-25.csv"
  file_land: 'covariates/FINAL.Process.Model.Observation.Covariates.12Jan2018.csv'

hpc_dev:
  data_repo: "/lustrefs/ceah/feral-swine/data"
  n_iter: 40000
